### ISSUE TITLE
Put NewLog() into LeKovr/go-base/log package

### ISSUE THREAD

**Issue by suntong** [LeKovr/go-base#1]
Hi Alex, 

Is it a good idea to put a NewLog() function into your LeKovr/go-base/log package? 

I think the following is really a typical usage,
https://github.com/LeKovr/teleproxy/blob/843f88a7873ca3fa989ba02b1a7fe5508e44f485/cmd/teleproxy/log.go#L11-L29
So it'll make more sense to include it in the package, not rewriting it everywhere else.

**Comment by LeKovr** [comment]
Nope, go-base/log is an interface which has no any dependencies.
Btw, I'm planning to use `gopkg.in/birkirb/loggers.v1` instead it.

**Comment by suntong** [comment]
OK. thanks for sharing gopkg.in/birkirb/loggers.v1
